
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package edu.uta.pcat;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRING_LITERAL = 3;
  public static final int ASGN = 35;
  public static final int SLASH = 39;
  public static final int UMINUS = 56;
  public static final int ELSIF = 13;
  public static final int LPAREN = 50;
  public static final int SEMI = 47;
  public static final int ARRAY = 7;
  public static final int MINUS = 37;
  public static final int FOR = 16;
  public static final int WRITE = 34;
  public static final int RPAREN = 51;
  public static final int REAL_LITERAL = 5;
  public static final int NOT = 21;
  public static final int IS = 18;
  public static final int AND = 6;
  public static final int LT = 40;
  public static final int RECORD = 27;
  public static final int TYPE = 31;
  public static final int OR = 23;
  public static final int COMMA = 48;
  public static final int DIV = 10;
  public static final int BEGIN = 8;
  public static final int GEQ = 43;
  public static final int PLUS = 36;
  public static final int LOOP = 19;
  public static final int EXIT = 15;
  public static final int IF = 17;
  public static final int DOT = 49;
  public static final int ID = 2;
  public static final int OF = 22;
  public static final int EOF = 0;
  public static final int RETURN = 28;
  public static final int BY = 9;
  public static final int error = 1;
  public static final int PROGRAM = 25;
  public static final int MOD = 20;
  public static final int NEQ = 45;
  public static final int EQ = 44;
  public static final int TIMES = 38;
  public static final int LSQBRA = 52;
  public static final int COLON = 46;
  public static final int LCUBRA = 54;
  public static final int ELSE = 12;
  public static final int READ = 26;
  public static final int TO = 30;
  public static final int WHILE = 33;
  public static final int RSQBRA = 53;
  public static final int RCUBRA = 55;
  public static final int THEN = 29;
  public static final int LEQ = 41;
  public static final int END = 14;
  public static final int GT = 42;
  public static final int VAR = 32;
  public static final int PROCEDURE = 24;
  public static final int DO = 11;
  public static final int INTEGER_LITERAL = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "STRING_LITERAL",
  "INTEGER_LITERAL",
  "REAL_LITERAL",
  "AND",
  "ARRAY",
  "BEGIN",
  "BY",
  "DIV",
  "DO",
  "ELSE",
  "ELSIF",
  "END",
  "EXIT",
  "FOR",
  "IF",
  "IS",
  "LOOP",
  "MOD",
  "NOT",
  "OF",
  "OR",
  "PROCEDURE",
  "PROGRAM",
  "READ",
  "RECORD",
  "RETURN",
  "THEN",
  "TO",
  "TYPE",
  "VAR",
  "WHILE",
  "WRITE",
  "ASGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "SLASH",
  "LT",
  "LEQ",
  "GT",
  "GEQ",
  "EQ",
  "NEQ",
  "COLON",
  "SEMI",
  "COMMA",
  "DOT",
  "LPAREN",
  "RPAREN",
  "LSQBRA",
  "RSQBRA",
  "LCUBRA",
  "RCUBRA",
  "UMINUS"
  };
}

